debug = false
logLevel = "INFO"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.traefik]
  address = ":8080"

[api]
  entryPoint = "traefik"
  dashboard = true

[kubernetes]

[http.middlewares]
  [http.middlewares.testHeader.headers]
    AccessControlAllowMethods= ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
    AccessControlAllowHeaders= ["*", "Authorization", "Content-Type", "Origin", "Content-Length"]
    AccessControlAllowOrigin = "*"
    AccessControlMaxAge = 100
    AddVaryHeader = true


# Metrics definition
[metrics]
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]
    # Name of the related entry point
    entryPoint = "traefik"

    # Buckets for latency metrics
    buckets = [0.1,0.3,1.2,5.0]