apiVersion: apps/v1
kind: Deployment
metadata:
  name: whitemos-deployment
spec: 
  replicas: 6
  selector:
    matchLabels:
      app: whitemos
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 1  # maxUnavailable define how many pods can be unavailable during the rolling update
  template:
    metadata:
      labels:
        app: whitemos
    spec:
      containers:
      - name: whitemos
        image: "jasonsoft/whitemos"
        ports:
        - containerPort: 10080