apiVersion: v1
kind: ReplicationController
metadata:
  name: whitemos-rc
spec: 
  replicas: 6
  selector:
    app: whitemos
  template:
    metadata:
      labels:
        app: whitemos
    spec:
      containers:
      - name: whitemos
        image: "jasonsoft/whitemos"
        ports:
        - containerPort: 10080